### ISSUE TITLE
Watch documentation unclear (I think)

### ISSUE THREAD

**Issue by MishaHerscu** [ga-wdi-boston/game-project-api#15]
I think the Watch documentation should say that you can only watch a game you have already joined. 

I know that a watcher requires a token, and it can be argued that this implies that you need to be in the game before you can watch, but when I was first learning how to use the given watcher code I thought the first step was to implement "Watch" as a streaming feature for third parties, and then the next step would be to use it as part of a multiplayer mode after that. I wasted a lot of time trying to get 3rd party streaming to work. I forget everything I tried, but here are some:
- Using your own auth token to watch, as if the API might not care who is watching, it is just there because the Game API always needs a token.
- Using another player's token 
- Using two different tokens (in a bunch of different ways)

Anyway, I couldn't get that to work, and I wasted a lot of time trying to do that. Once I knew you had to be in the game to watch, the actual feature of just automatically setting up a watcher when you make a game or join a game is really easy, it is just basically the same Ajax call as everything else.

**Comment by gaand** [comment]
You make a good case.  I've thought of allowing watching without being in the game (just logged in).  I may try to implement that.

I think because you can only list your games (ones you've created or joined) that ought to make you think you can't watch other games (how would you get there IDs?).  But, I suppose someone could send you and ID out of band as is required to join a game.

I'll definitely consider changes on the next iteration.

**Comment by MishaHerscu** [comment]
Okay thanks. Yeah, I can see the argument either way. I probably should have thought of that faster when I was working on it. Thanks.
